### PR TITLE
Spring boot 2 upgrade

### PR DESCRIPTION
**Pull request by jdfox**
# What and why?
Spring Boot 1.x had its end-of-life in August 2019. 
Maintenance for Spring Boot 2.1 ended in November 2020, and 2.2 ends in July, so it's time to upgrade Spring Boot to 2.3+. 

Updating Spring Framework to 5.3, and Spring Boot to 2.4, stepwise by minor version.
Updating lib dependencies, removed Spring Cloud, migrated most deprecated config in YAML, apart from security.  

# How to test?
- `mvn clean install`
- `mvn spring-boot:run`
- deploy to dev cluster, and run acceptance tests there 
- set port forwarding from localhost 
- functional testing TBA...
# Trello
- https://trello.com/c/qIpvr8ai

### CODE REVIEW

**Comment by warrenbailey** [comment]
I think this fails to deploy as it's creating the liquibase tables in the public schema, we had a similar. issue with both sample and iac. Might need to set the liquibase schema name setting

See example https://github.com/ONSdigital/iac-service/pull/74/files

**Review by insacuri — APPROVED** [review]

**Pull request merged**
