### PR TITLE
Migrate from Spring Boot 2.4.x

### PR DESCRIPTION
**Pull request by mfcrocker**
# What and why?

# How to test?

# Trello

### CODE REVIEW

**Comment by pricem14pc** [comment]
@anwilkie this is now building and deploying as expected. I've successfully tested;

- deploying into an existing persistent environment with a pre-existing `casesvc` schema
- deploying into a new env with no pre-existing `casesvc` schema

for both the above the acceptance tests run successfully, and Rops and frontstage behaving as expected

**Comment by insacuri** [comment]
We managed to migrate to 2.6.6 in another PR so closing this

**Pull request closed without merging**
